* Info
** DMMS - Distributed multimedia systems
** ND - Networks and distributed systems
** PSE - Programming and software engineering
** GI - Global infrastructures
** PMA - Precise modeling and analysis
** LogID - Logic and Intelligent Data
** WNaS - Wireless Networks and Security
* Ideas
** Shared Buffer done right
*** http://static.googleusercontent.com/media/research.google.com/no//pubs/archive/41895.pdf
*** P2P http://dl.acm.org/citation.cfm?id=1180916 [[file:p259-oster.pdf][lokal-pdf]]
*** Duplex http://dl.acm.org/citation.cfm?id=192900 [[file:p165-pacull.pdf][local-pdf]]
*** TLA+ http://research.microsoft.com/en-us/um/people/lamport/tla/formal-methods-amazon.pdf
** A new language
*** The StackOverflow structure
    Create a language which is at its core very (very) small. It won't have
    any libraries. No development will be done in the language; it has no
    central ownership, nor is it headed in any particular direction. Instead
    it will consist of small modules. Every module will automatically be
    available for everyone (maybe allow exceptions?). All modules will be
    searchable, and they can be up- and down-voted. Popular modules will
    greatly influence the language, and be present in a lot of programs. The
    users of the language decide what direction the language is headed, and
    they will participate implicitly by using modules.
*** http://www.chrisseaton.com/katahdin/katahdin.pdf
    
** A javascript markdown viewer
   Make an alternative markdown to html, and using javascript to typeset the
   document.

* First semester
** Courses
** INF4130
** INF4820
** INF5780
